version: "3"

services:
    next:
        build: ./entree-client-next
        ports:
            - 4200:4200
        volumes:
            - ./entree-client-next/:/next-app

    express_app:
        build: ./server
        ports:
            - 3000:3000
        volumes:
            - ./server/:/app
        environment:
            - DB_NAME=entrees
            - DB_HOST=mongo
            - DB_PORT=3306
            - DB_USER=root
            - DB_PASSWORD=rootpassword
            - JWT_SECRET=DFM312JUX09Q234NA
        depends_on:
            - mongo
        command: "bash start.sh mongo:27017"

    mongo:
        container_name: mongo
        image: mongo:latest
        ports:
            - "27017:27017"
            



